vnet_name                         = "kiosk-vnet"
api_management_subnet_name        = "kiosk-api-management-subnet"
api_management_delegation_name    = "kiosk-api-management-delegation"
api_management_nsg_name           = "kiosk-api-management-nsg"
private_endpoints_subnet_name     = "kiosk-private-endpoints-subnet"
private_endpoints_nsg_name        = "kiosk-private-endpoints-nsg"
dns_zone_name                     = "kiosk-dns-zone"
