name: DEVELOP-CI-CD

on:
  push:
    branches:
      - develop

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  validate:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: terraform validate
        run: . ./terraform-runner.sh develop validate

  init:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: terraform init
        run: . ./terraform-runner.sh develop init

  plan:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: terraform plan
        run: . ./terraform-runner.sh develop plan

  apply:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: terraform apply
        run: . ./terraform-runner.sh develop apply
