# pipeline won't run succesfully due to lack of azure student account permissions

name: PRODUCTION-CI-CD

on:
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: terraform init
        run: . ./terraform-runner.sh production init

      - name: terraform plan
        run: . ./terraform-runner.sh production plan

      - name: terraform apply
        run: . ./terraform-runner.sh production apply
